const texts = {
  pl: {
    nav: {
      projects: 'Projekty',
      about: 'O mnie',
      contact: 'Kontakt',
      available: 'Otwarty na oferty',
      getInTouch: 'Napisz do mnie',
    },
    hero: {
      badge: 'Dostępny · Polska / zdalnie',
      headline1: 'Fullstack developer,',
      headline2: 'buduję',
      headline3: 'nowoczesne aplikacje.',
      sub: 'Jestem ',
      name: 'Paweł Nowicki',
      subEnd: ' — tworzę szybkie, responsywne aplikacje webowe z dbałością o design i wydajność. Specjalizuję się w React i Node.js.',
      viewProjects: 'Zobacz projekty',
      contact: 'Napisz do mnie',
      downloadCV: 'Pobierz CV',
    },
    stack: {
      label: 'technologie',
      heading1: 'Narzędzia, po które sięgam',
      heading2: '— dobrane z potrzeby, nie z mody.',
      desc: 'Skupiam się na wąskim, sprawdzonym zestawie technologii. Każda z nich obsługiwała produkcję pod moim nadzorem.',
    },
    projects: {
      label: 'projekty',
      heading: 'Wybrane prace.',
      demo: 'Demo',
      github: 'GitHub',
    },
    about: {
      label: 'o mnie',
      heading1: 'Kod, design',
      heading2: 'i szczegóły.',
      text: 'Jestem fullstack developerem z zamiłowaniem do tworzenia nowoczesnych, szybkich i w pełni responsywnych aplikacji internetowych. Specjalizuję się w technologiach takich jak React, Node.js, Express, tworząc rozwiązania, które łączą estetykę z funkcjonalnością. Każdy projekt traktuję indywidualnie — dbam o detale, bezpieczeństwo i wysoką wydajność. Nieustannie rozwijam swoje umiejętności, śledzę najnowsze trendy i wierzę, że dobrze zaprojektowana aplikacja powinna być nie tylko użyteczna, ale też przyjemna w odbiorze.',
      downloadCV: 'Pobierz CV',
      principles: {
        title: 'Zasady pracy',
        items: [
          'Prosta architektura, ciekawy produkt.',
          'Responsywność to standard, nie dodatek.',
          'Czysty kod zamiast szybkich skrótów.',
          'Dostępność przed efektami.',
          'Kod pisany z myślą o następnym developerze.',
        ],
      },
    },
    contact: {
      label: 'kontakt',
      heading1: 'Masz ciekawy',
      heading2: 'projekt?',
      sub: 'Aktualnie otwarty na oferty pracy oraz projekty freelance. Najszybciej odpisuję na e-mail — zazwyczaj tego samego dnia.',
      namePlaceholder: 'Twoje imię',
      emailPlaceholder: 'Twój e-mail',
      messagePlaceholder: 'Twoja wiadomość...',
      send: 'Wyślij wiadomość',
      sending: 'Wysyłanie...',
      successMsg: 'Wiadomość wysłana! Odezwę się wkrótce.',
      errorMsg: 'Coś poszło nie tak. Spróbuj ponownie.',
      direct: 'bezpośrednio',
    },
    footer: {
      status: 'wszystko działa poprawnie',
      copyright: '© 2026 Paweł Nowicki',
      tagline: 'zbudowane z pasją',
    },
  },

  en: {
    nav: {
      projects: 'Projects',
      about: 'About',
      contact: 'Contact',
      available: 'Open to work',
      getInTouch: 'Get in touch',
    },
    hero: {
      badge: 'Available · Poland / remote',
      headline1: 'Fullstack developer,',
      headline2: 'building',
      headline3: 'modern applications.',
      sub: "I'm ",
      name: 'Paweł Nowicki',
      subEnd: ' — I craft fast, responsive web applications with care for design and performance. Specializing in React and Node.js.',
      viewProjects: 'View projects',
      contact: 'Get in touch',
      downloadCV: 'Download CV',
    },
    stack: {
      label: 'stack',
      heading1: 'The tools I reach for',
      heading2: '— chosen for fit, not fashion.',
      desc: 'I keep a deliberately narrow toolbox. Each item below has carried production traffic under my watch.',
    },
    projects: {
      label: 'projects',
      heading: 'Selected work.',
      demo: 'Demo',
      github: 'GitHub',
    },
    about: {
      label: 'about',
      heading1: 'Code, design',
      heading2: 'and details.',
      text: "I'm a fullstack developer passionate about building modern, fast, and fully responsive web applications. I specialize in technologies like React, Node.js, Express — crafting solutions that balance functionality with design. I approach every project with care for detail, security, and performance. Constantly improving my skills and staying up-to-date with industry trends, I believe great software should not only work flawlessly but also look and feel amazing.",
      downloadCV: 'Download CV',
      principles: {
        title: 'Working principles',
        items: [
          'Simple architecture, interesting product.',
          'Responsiveness is a standard, not a bonus.',
          'Clean code over quick shortcuts.',
          'Accessibility before effects.',
          'Code written for the next developer.',
        ],
      },
    },
    contact: {
      label: 'contact',
      heading1: 'Have an interesting',
      heading2: 'project?',
      sub: "Currently open to job offers and freelance projects. Fastest to reach me by email — I usually reply the same day.",
      namePlaceholder: 'Your name',
      emailPlaceholder: 'Your email',
      messagePlaceholder: 'Your message...',
      send: 'Send message',
      sending: 'Sending...',
      successMsg: 'Message sent! I\'ll get back to you soon.',
      errorMsg: 'Something went wrong. Please try again.',
      direct: 'direct',
    },
    footer: {
      status: 'all systems operational',
      copyright: '© 2026 Paweł Nowicki',
      tagline: 'built with care',
    },
  },
};

export const projectsList = [
  {
    title: 'Hematobieg',
    titleEn: 'Hematobieg',
    descPl: 'Projekt komercyjny promujący bieg na rzecz walki z białaczką.',
    descEn: 'A commercial project promoting a charity run supporting leukemia patients.',
    image: 'hematobieg',
    demo: 'https://hematobieg.org/',
    github: 'https://github.com/pawelnowicki87/hematobieg',
    tags: ['React', 'JavaScript', 'CSS'],
  },
  {
    title: 'Phone Catalog',
    titleEn: 'Phone Catalog',
    descPl: 'Projekt sklepu z telefonami oraz akcesoriami do urządzeń mobilnych.',
    descEn: 'An online store for phones and mobile accessories.',
    image: 'phonecatalog',
    demo: 'https://pawelnowicki87.github.io/react_phone-catalog/',
    github: 'https://github.com/pawelnowicki87/phone_catalog_react',
    tags: ['React', 'Redux', 'TypeScript'],
  },
  {
    title: 'Welcome to the MET',
    titleEn: 'Welcome to the MET',
    descPl: 'Statyczna w pełni responsywna strona muzeum wraz z formularzem kontaktowym.',
    descEn: 'A fully responsive static museum website with a contact form.',
    image: 'welcome',
    demo: 'https://pawelnowicki87.github.io/welcome_to_the_met/',
    github: 'https://github.com/pawelnowicki87/welcome_to_the_met',
    tags: ['HTML', 'CSS', 'JavaScript'],
  },
  {
    title: 'Todo App',
    titleEn: 'Todo App',
    descPl: 'Lista do zarządzania zadaniami z filtrowaniem aktywnych i wykonanych.',
    descEn: 'A task manager with filtering for active and completed tasks.',
    image: 'todo',
    demo: 'https://pawelnowicki87.github.io/todo_app_with_api_react/',
    github: 'https://github.com/pawelnowicki87/todo_app_with_api_react',
    tags: ['React', 'API', 'JavaScript'],
  },
  {
    title: 'Lista postów',
    titleEn: 'List of Posts',
    descPl: 'Aplikacja do zarządzania postami oraz komentarzami z użyciem Redux.',
    descEn: 'An app for managing posts and comments using Redux.',
    image: 'listofposts',
    demo: 'https://pawelnowicki87.github.io/list_of_posts_react_redux/',
    github: 'https://github.com/pawelnowicki87/list_of_posts_react_redux',
    tags: ['React', 'Redux', 'REST API'],
  },
  {
    title: 'Gra 2048',
    titleEn: 'Game 2048',
    descPl: 'Gra relaksacyjna do ćwiczenia umysłu.',
    descEn: 'A relaxing logic puzzle game.',
    image: 'game',
    demo: 'https://pawelnowicki87.github.io/2048_game/',
    github: 'https://github.com/pawelnowicki87/2048_game',
    tags: ['JavaScript', 'HTML', 'CSS'],
  },
];

export default texts;
